# Generated by Django 6.0 on 2026-06-28 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genres', models.JSONField(default=list)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], max_length=10)),
            ],
            options={
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='WatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLAN', 'Plan to Watch'), ('WATCHING', 'Watching'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('WAITING', 'Waiting to be Released')], default='PLAN', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
    ]
